### ISSUE TITLE
db-to-csv comment list output

### ISSUE THREAD

**Issue by TevenLeScao** [bencabrera/grawitas#11]
Hello and thanks for this great tool !

When running the db_export CLI tool on a database containing the English Wikipedia with the comment-list-csv flag, I receive a file that only contains the headers of the columns, repeated ad nauseam (for example, a few dozen thousands of id | parent_id | user | date | section | article | text). The json comment list actually contains information. Is this an issue you have met before ?

Thanks in advance,

Teven.

**Comment by bencabrera** [comment]
Hi Teven,

thanks for the report. Indeed there was a typo that led the program to export the header line instead of the actual comment. Should be fixed by now. I will fix another bug I found and then build a new Windows release - if you are using that.

Ben

**Comment by TevenLeScao** [comment]
Just tested it on Linux and it works just fine !

Thanks,

Teven.
