### ISSUE TITLE
Add a kind of sanity check for the input of the crawler component

### ISSUE THREAD

**Issue by bencabrera** [bencabrera/grawitas#6]
E.g. check that the article names do not start with Talk:

**Comment by bjoernross** [comment]
The paper says:
> The  program expects  a  text  file  containing  the  URLs  to  the Wikipedia  articles  as  input.  

So we should also ensure that it works when the text file contains URLs.

**Comment by bencabrera** [comment]
Fixed in 080e6a36b3f7850f9adc6f4a1f45c555d051c73e. When using URLs users are now notified that they should rather use article titles.
