### ISSUE TITLE
error: Failure "Es konnte keine SSL-Kontextstruktur erzeugt werden<>"

### ISSUE THREAD

**Issue by julbre** [bencabrera/grawitas#7]
It does not work, neither with grawitas_gui nor with crawler-components. I always get the same errors, although I´ve installed  Microsoft Visual C++ Redistributable for Visual Studio 2017.
![ssl](https://user-images.githubusercontent.com/27731950/32901396-ffdbb642-caef-11e7-8a88-a4a0f50ff669.PNG)
The GUI-Interface and command-line stated "Finished crawling and parsing provided article", but there wasn´t any parsed site as output in the output-folder. 
Do you have any ideas, what´s going wrong?

**Comment by bencabrera** [comment]
Should be fixed in latest release. In d44cadacb8a692e8fb3562a0a4686b3d7773ff50 we switched from the QT5 Network library to CURL which should take care of some of the weird SSL errors.
