### ISSUE TITLE
Windows 10 64x Error nach Crawler Component (GML)

### ISSUE THREAD

**Issue by davidkhano** [bencabrera/grawitas#8]
Nachdem ich das Programm normal und in der Powershell gestartet habe, stürzt das Programm nach dem Durchsuchen des letzten Archivs ab. 
Es wurden Dateien erstellt, jedoch blieben diese Leer.
Die Windows Powershell konnte ausserdem keine Error Message aufnehmen.

Barack_Obama.user_network.gml

Barack_Obama_raw.wikimd

![image](https://user-images.githubusercontent.com/28726803/32950579-171289fa-cba7-11e7-92ac-1e7b987772ff.png)

!!EDIT!!

Die .wikimd Datei ist 15,4mb groß und musste in eine .txt umgewandelt werden, um diese hier hochzuladen. 

[Barack_Obama_raw.txt](https://github.com/bencabrera/grawitas/files/1482516/Barack_Obama_raw.txt)

**Comment by bencabrera** [comment]
Ich werde das heute nachmittag nochmal auf einem Rechner bei uns testen und dann melde ich mich.

**Comment by bencabrera** [comment]
Ich konnte den Fehler jetzt bei mir reproduzieren und habe auch eine Vermutung, woran das liegt. Werde aber wahrscheinlich erst morgen dazu kommen, den zu beheben.

**Comment by bencabrera** [comment]
Should be fixed with latest release. 48fea5dcf19f6c69c2bc52d251a1c425a302a39c
